name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:  
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL
        run: echo "SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True" >> $GITHUB_ENV
      - uses: fastai/workflows/quarto-ghp@master
        with:
          version: '3.11'